# Generated by Django 5.1.14 on 2025-11-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='resguardo',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='tipo_servicio_otro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='tipos_servicio',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('instalacion', 'Instalación'), ('configuracion', 'Configuración'), ('mantenimiento', 'Mantenimiento'), ('garantia', 'Garantía'), ('revision', 'Falla/Revisión'), ('capacitacion', 'Capacitación')], max_length=20),
        ),
    ]
